#on: [push]  
#  schedule:
#  - cron: "5,14,26,38,53 * * * *"
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1,10,20,30,40,50 * * * *'


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:               
    - name: bookmana blog
      uses: actions/checkout@master
    - name: git config
      env:
        USER_NAME: ${{ github.event.pusher.name }}
        USER_EMAIL: ${{ github.event.pusher.email }}
      run: |
        git config --global user.email "$USER_EMAIL"
        git config --global user.name "$USER_NAME"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  
    - name: install deploy keys
      env:
        GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      
    - name: clone static_site_repo
      run: |
        cd ..
        mkdir static_site_repo              
        git clone git@github.com:bookmana/bookmana.github.io.git static_site_repo


    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r py/requirements.txt
    
    - name: python run
      run: |
        python py/main.py
      env: 
        NV_CENTER_API: ${{ secrets.NV_CENTER_API }}
        PARK_API_KEY: ${{ secrets.PARK_API_KEY }}
        DB_INFO: ${{ secrets.DB_INFO }}
        
    - name: push changed files    
      run: |
        cd ../static_site_repo
        git add --all
        git commit -m "autocommit"        
        git push -u origin main
        
 
