name: Pylint

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:               
    - name: bookmana blog
      uses: actions/checkout@master
      with:
        path: 'static-site-generator'
         
    - name: git config
      env:
        USER_NAME: ${{ github.event.pusher.name }}
        USER_EMAIL: ${{ github.event.pusher.email }}
      run: |
        git config --global user.email "$USER_EMAIL"
        git config --global user.name "$USER_NAME"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  
    - name: install deploy keys
      env:
        GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      
    - name: clone static_site_repo
      run: |
        pwd        
        echo "1"
        cd ..
        pwd        
        echo "2"
        mkdir static_site_repo
        ls
        pwd        
        git clone git@github.com:bookmana/bookmana.github.io.git static_site_repo
        ls

    - name: move build files to static files repo
      run: |
        cd ../static_site_repo
        echo "3"       
        touch aa.txt
        ls
        pwd
        
      
    - name: push changed files
      run: |
        cd ../static_site_repo
        git add .
        git commit -m "autocommit"
        git push origin master
