name: Pylint

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/hub-create-repos
      env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
         
    - name: clone gatsby-blog
      uses: actions/checkout@master
      with:
        path: 'static-site-generator'
    - name: git config
      env:
        USER_NAME: ${{ github.event.pusher.name }}
        USER_EMAIL: ${{ github.event.pusher.email }}
      run: |
        git config --global user.email "$USER_EMAIL"
        git config --global user.name "$USER_NAME"

  #  - name: make deploy keys
  #    env:
  #      GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
  #    run: |
  #      mkdir -p ~/.ssh/
  #      echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
  #      chmod 600 ~/.ssh/id_rsa
  #      ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: clone static_site_repo
      run: |
        cd ..
        gh auth status
        echo "1"        
        gh auth login --with-token process.env.GITHUB_TOKEN 
        echo "2"
        gh auth status
        echo "3"
        gh repo clone bookmana/bookmana static_site_repo


    - name: move build files to static files repo
      run: |
        pwd
        cd static_site_repo
        pwd
        cd ../static_site_repo
        
  #  - name: push changed files
  #    run: |
  #      cd ../static_site_repo
  #      git add .
  #      git commit -m "$(git -C ../static-site-generator/ log --format=%B -n 1)"
  #      git push origin master
