name: bookmana action

on:
  schedule:
  - cron: "11,25,42,58 1-23 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r py/requirements.txt
    - name: Analysing the code with pylint
      run: |
        python py/test.py
